Jenkinsfile_CNP
build.gradle

https://tools.hmcts.net/jira/browse/RDM-12809
Configure project pipeline
```
[ ] Yes
[x] No
```

RDM-12809 Configure sonarqube

---

charts/ccd-case-disposer/Chart.yaml
charts/ccd-case-disposer/values.yaml
src/integrationTest/java/uk/gov/hmcts/reform/ccd/ApplicationParametersIntegrationTest.java
src/integrationTest/java/uk/gov/hmcts/reform/ccd/data/dao/CaseDataRepositoryIntegrationTest.java
src/integrationTest/resources/application-test.yaml
src/main/java/uk/gov/hmcts/reform/ccd/ApplicationParameters.java
src/main/java/uk/gov/hmcts/reform/ccd/service/CaseDeletionService.java
src/main/resources/application.yaml
src/test/java/uk/gov/hmcts/reform/ccd/service/CaseDeletionServiceTest.java

https://tools.hmcts.net/jira/browse/RDM-12839
Add DELETE_CASE_TYPES to hold case_type_ids for which case deletion applies.
```
[ ] Yes
[x] No
```

RDM-12839 Add DELETE_CASE_TYPES

---

charts/ccd-case-disposer/Chart.yaml

https://tools.hmcts.net/jira/browse/CCD-2579
```
[ ] Yes
[ ] No
```

helm chart update

---

build.gradle
charts/ccd-case-disposer/values.preview.template.yaml
config/owasp/suppressions.xml
src/integrationTest/java/uk/gov/hmcts/reform/ccd/data/es/CaseDataElasticsearchOperationsIntegrationTest.java
src/integrationTest/java/uk/gov/hmcts/reform/ccd/data/es/TestElasticsearchFixture.java
src/main/java/uk/gov/hmcts/reform/ccd/data/es/CaseDataElasticsearchOperations.java
src/test/java/uk/gov/hmcts/reform/ccd/data/es/CaseDataElasticsearchOperationsTest.java

https://tools.hmcts.net/jira/browse/LAU-327
Upgrade Elastic Search Client
```
[ ] Yes
[x] No
```

LAU-327 Upgrade Elastic Search Client

---

config/owasp/suppressions.xml

--Adding the Suppression for Spring Beans jar. Temporary fix.

---

build.gradle

https://tools.hmcts.net/jira/browse/CCD-2929
```
[ ] Yes
[ ] No
```

spring framework versiyon update to 5.3.18 from 5.3.15

---

build.gradle
charts/ccd-case-disposer/values.preview.template.yaml
config/owasp/suppressions.xml
src/integrationTest/java/uk/gov/hmcts/reform/ccd/data/es/CaseDataElasticsearchOperationsIntegrationTest.java
src/integrationTest/java/uk/gov/hmcts/reform/ccd/data/es/TestElasticsearchFixture.java
src/main/java/uk/gov/hmcts/reform/ccd/data/es/CaseDataElasticsearchOperations.java
src/test/java/uk/gov/hmcts/reform/ccd/data/es/CaseDataElasticsearchOperationsTest.java

Reverts hmcts/ccd-case-disposer#26

Revert "LAU-327 Upgrade Elastic Search Client"

---

config/owasp/suppressions.xml

Suppresion for spring-core-5.3.18.jar relate dependency check failure.
```
[ ] Yes
[x ] No
```

Spring-core-5.3.18.jar dependency issue suppression

---

Jenkinsfile_CNP

Fix attempt for broken pipeline - hoping CHANGE_ID is also available as an env var
```
[ ] Yes
[X] No
```

try using change id from env vars

---

Jenkinsfile_CNP

https://tools.hmcts.net/jira/browse/CCD-3122

use env.BRANCH_NAME

---

Jenkinsfile_CNP

https://tools.hmcts.net/jira/browse/CCD-3122
disable build-breaking line
```
[X] Yes
[ ] No
```

disable build-breaking line

---

infrastructure/variables.tf

https://tools.hmcts.net/jira/browse/LAU-325
Remove deployment_namespace from variables.tf.
```
[ ] Yes
[x] No
```

LAU-325: Removing deployment_namespace var

---

build.gradle
config/owasp/suppressions.xml

https://tools.hmcts.net/jira/browse/CCD-3294
Removed suppression and updated spring-framework.version to 5.3.20
```
[ ] Yes
[X] No
```

CCD-3294: Removed suppression and updated spring-framework.version to 5.3.20

---

charts/ccd-case-disposer/Chart.yaml
charts/ccd-case-disposer/values.yaml
src/functionalTest/java/uk/gov/hmcts/reform/ccd/constants/TestConstants.java
src/functionalTest/java/uk/gov/hmcts/reform/ccd/parameter/TestParameterResolver.java
src/integrationTest/java/uk/gov/hmcts/reform/ccd/CaseDeletionIntegrationTest.java
src/integrationTest/java/uk/gov/hmcts/reform/ccd/config/TestParameterResolver.java
src/integrationTest/java/uk/gov/hmcts/reform/ccd/config/WireMockStubs.java
src/integrationTest/java/uk/gov/hmcts/reform/ccd/constants/TestConstants.java
src/integrationTest/java/uk/gov/hmcts/reform/ccd/data/TestDataProvider.java
src/integrationTest/java/uk/gov/hmcts/reform/ccd/utils/RoleDeleteTestUtils.java
src/integrationTest/resources/application-test.yaml
src/main/java/uk/gov/hmcts/reform/ccd/data/am/RoleAssignmentsDeletePostRequest.java
src/main/java/uk/gov/hmcts/reform/ccd/data/am/RoleAssignmentsQueryRequest.java
src/main/java/uk/gov/hmcts/reform/ccd/exception/RoleAssignmentDeletionException.java
src/main/java/uk/gov/hmcts/reform/ccd/parameter/DefaultParameterResolver.java
src/main/java/uk/gov/hmcts/reform/ccd/parameter/ParameterResolver.java
src/main/java/uk/gov/hmcts/reform/ccd/service/CaseDeletionService.java
src/main/java/uk/gov/hmcts/reform/ccd/service/remote/DisposeDocumentsRemoteOperation.java
src/main/java/uk/gov/hmcts/reform/ccd/service/remote/DisposeRoleAssignmentsRemoteOperation.java
src/main/java/uk/gov/hmcts/reform/ccd/util/RestConstants.java
src/main/java/uk/gov/hmcts/reform/ccd/util/SecurityUtil.java
src/main/java/uk/gov/hmcts/reform/ccd/util/log/RoleDeletionRecordHolder.java
src/main/resources/application.yaml
src/test/java/uk/gov/hmcts/reform/ccd/parameter/DefaultParameterResolverTest.java
src/test/java/uk/gov/hmcts/reform/ccd/service/CaseDeletionServiceTest.java
src/test/java/uk/gov/hmcts/reform/ccd/service/remote/DisposeDocumentsRemoteOperationTest.java
src/test/java/uk/gov/hmcts/reform/ccd/service/remote/DisposeRoleAssignmentsRemoteOperationTest.java
src/test/java/uk/gov/hmcts/reform/ccd/util/log/RoleDeletionRecordHolderTest.java

https://tools.hmcts.net/jira/browse/LAU-328
Delete Associated Case Roles
[ ] Yes
[x] No

Integration of role assignment deletion into case disposer

---

Jenkinsfile_CNP

https://tools.hmcts.net/jira/browse/LAU-414
Disable SS Upload for AAT.
```
[ ] Yes
[x] No
```

LAU-325: Disable SS upload for AAT.

---

Jenkinsfile_CNP
charts/ccd-case-disposer/Chart.yaml
charts/ccd-case-disposer/values.yaml
src/functionalTest/java/uk/gov/hmcts/reform/ccd/helper/GlobalSearchIndexCreator.java
src/functionalTest/resources/application-functional.yaml

Update s2s client secret alias
```
[ ] Yes
[x] No
```

Update s2s client secret alias.

---

Jenkinsfile_CNP
Jenkinsfile_nightly

https://tools.hmcts.net/jira/browse/LAU-325
Add nightly jenkinsfille and capture missing secret.
```
[ ] Yes
[x] No
```

LAU-325: Add Jenkinsfile_nightly and add missing secret

---

Jenkinsfile_CNP

Update Jenkinsfile to sync master with demo and perftest
```
[ ] Yes
[x] No
```

Update Jenkinsfile to sync master with demo and perftest

---

charts/ccd-case-disposer/Chart.yaml
src/main/resources/application.yaml

https://tools.hmcts.net/jira/browse/LAU-324
Trigger build.
```
[ ] Yes
[x] No
```

LAU-324: Update to trigger build.

---

charts/ccd-case-disposer/Chart.yaml
charts/ccd-case-disposer/values.yaml

https://tools.hmcts.net/jira/browse/LAU-324
Update to change type to job.
```
[ ] Yes
[x] No
```

LAU-324: Update to fix build.

---

Jenkinsfile_CNP
charts/ccd-case-disposer/Chart.yaml

https://tools.hmcts.net/jira/browse/LAU-325
Add missing app-insights key.
```
[ ] Yes
[x] No
```

LAU-325: Correction to app-insights key.

---

Jenkinsfile_CNP
charts/ccd-case-disposer/Chart.yaml
src/functionalTest/java/uk/gov/hmcts/reform/ccd/CaseDeletionFunctionalTest.java
src/functionalTest/java/uk/gov/hmcts/reform/ccd/TestDataProvider.java
src/functionalTest/java/uk/gov/hmcts/reform/ccd/utils/ElasticSearchTestUtils.java

https://tools.hmcts.net/jira/browse/LAU-325
Disable ES for preview
```
[ ] Yes
[x] No
```

Functional tests

---

charts/ccd-case-disposer/Chart.yaml
charts/ccd-case-disposer/values.yaml

https://tools.hmcts.net/jira/browse/LAU-381
Add missing ES host.
```
[ ] Yes
[x] No
```

LAU-381: Adding missing ES host.

---

charts/ccd-case-disposer/Chart.yaml
src/integrationTest/resources/application-test.yaml
src/main/resources/application.yaml

Update ES node urls.
```
[ ] Yes
[ ] No
```

Update ES node urls.

---

config/owasp/suppressions.xml

https://tools.hmcts.net/jira/browse/CCD-3442
CCD-3442  : Update suppressions.xml temporary suppression for CVE-2022-33915
```
[ ] Yes
[X] No
```

CCD-3442  : Update suppressions.xml temporary suppression for CVE-2022-33915

---

src/main/java/uk/gov/hmcts/reform/ccd/service/remote/DisposeDocumentsRemoteOperation.java
src/test/java/uk/gov/hmcts/reform/ccd/service/remote/DisposeDocumentsRemoteOperationTest.java

Update document dispose exception handling
```
[ ] Yes
[X] No
```

Update document dispose exception handling

---

src/functionalTest/java/uk/gov/hmcts/reform/ccd/utils/DocumentDeleteTestUtils.java
src/main/java/uk/gov/hmcts/reform/ccd/service/remote/DisposeDocumentsRemoteOperation.java

Change document store functional tests assertions
```
[ ] Yes
[X] No
```

Change document store functional tests assertions

---

build.gradle
charts/ccd-case-disposer/Chart.yaml

https://tools.hmcts.net/jira/browse/CCD-965
CCD-965: Remove Temporary Sonar Exclusions ccd-case-disposer
**Does this PR introduce a breaking change?**
```
[ ] Yes
[x] No
```

CCD-965: Remove Temporary Sonar Exclusions ccd-case-disposer

---

src/main/resources/application.yaml

Disable show sql in the logs.
```
[ ] Yes
[X] No
```

Disable show sql in the logs.

---

src/main/java/uk/gov/hmcts/reform/ccd/util/SecurityUtil.java
src/test/java/uk/gov/hmcts/reform/ccd/util/SecurityUtilTest.java

https://tools.hmcts.net/jira/browse/LAU-458
Performance: Cache user credentials
```
[ ] Yes
[x] No
```

LAU-458 Performance: Cache user credentials

---

build.gradle
config/owasp/suppressions.xml

https://tools.hmcts.net/jira/browse/CCD-3515
CVE-2022-22976
```
[ ] Yes
[ x] No
```

Ccd 3515 CVE 2022 22976

---

src/functionalTest/resources/application-functional.yaml
src/main/resources/application.yaml

https://tools.hmcts.net/jira/browse/LAU-467
Add environment variable for table log size summary.
```
[ ] Yes
[x] No
```

LAU-462: Allow table summary log size to change.

---

charts/ccd-case-disposer/Chart.yaml

https://tools.hmcts.net/jira/browse/LAU-454
Trigger prod pipeline.
```
[ ] Yes
[x] No
```

LAU-454: Trigger prod pipeline.

---

charts/ccd-case-disposer/Chart.yaml
charts/ccd-case-disposer/values.preview.template.yaml
src/main/java/uk/gov/hmcts/reform/ccd/ApplicationExecutor.java
src/main/java/uk/gov/hmcts/reform/ccd/parameter/DeletableCaseTypePropertyInterceptor.java
src/main/java/uk/gov/hmcts/reform/ccd/service/CaseDeletionLoggingService.java
src/main/java/uk/gov/hmcts/reform/ccd/service/CaseDeletionResolver.java
src/main/java/uk/gov/hmcts/reform/ccd/service/CaseDeletionService.java
src/main/java/uk/gov/hmcts/reform/ccd/service/remote/DisposeDocumentsRemoteOperation.java
src/main/java/uk/gov/hmcts/reform/ccd/util/SummaryStringLogBuilder.java
src/test/java/uk/gov/hmcts/reform/ccd/ApplicationExecutorTest.java
src/test/java/uk/gov/hmcts/reform/ccd/service/CaseDeletionLoggingServiceTest.java
src/test/java/uk/gov/hmcts/reform/ccd/service/CaseDeletionResolverTest.java

https://tools.hmcts.net/jira/browse/LAU-469
Show summary logs even if no cases are eligible for deletion
```
[ ] Yes
[x] No
```

Show summary logs even if no cases are eligible for deletion

---

src/main/java/uk/gov/hmcts/reform/ccd/exception/IdamAuthTokenGenerationException.java
src/main/java/uk/gov/hmcts/reform/ccd/exception/ServiceAuthTokenGenerationException.java
src/main/java/uk/gov/hmcts/reform/ccd/util/SecurityUtil.java
src/test/java/uk/gov/hmcts/reform/ccd/util/SecurityUtilTest.java

Add idam and service auth exception handling
```
[ ] Yes
[x] No
```

Add idam and service auth exception handling

---

config/owasp/suppressions.xml

CCD-3603 (https://tools.hmcts.net/jira/browse/CCD-3603)
Updated suppressions file to temporarily suppress CVE-2022-31197.
```
[ ] Yes
[x] No
```

CCD-3603: Temporarily suppress CVE-2022-31197

---

build.gradle
config/owasp/suppressions.xml

https://tools.hmcts.net/jira/browse/LAU-490
Upgrade postgres library to 42.4.1.
```
[ ] Yes
[x] No
```

LAU-490: Postgres library upgrade.

---

infrastructure/main.tf

https://tools.hmcts.net/jira/browse/LAU-470
Update to remove preview network permissions.
```
[ ] Yes
[x] No
```

LAU-470: Update permissions.

---

charts/ccd-case-disposer/Chart.yaml
infrastructure/main.tf

https://tools.hmcts.net/jira/browse/LAU-470
Put back preview vnet aks db rules.
```
[ ] Yes
[x] No
```

LAU-470: Put back preview vnet rules.

---

config/owasp/suppressions.xml

https://tools.hmcts.net/jira/browse/CCD-3577
Cleanup CVE Suppressions 
```
[ ] Yes
[x ] No
```

CCD-3577 Cleanup CVE Suppressions 

---

build.gradle

https://tools.hmcts.net/jira/browse/LAU-521
This change is to fix dependency check related to snakeyml version
```
[ ] Yes
[x] No
```

LAU-521 Snakeyml dependency check fix

---

config/owasp/suppressions.xml

Added CVE suppression

---

src/main/java/uk/gov/hmcts/reform/ccd/service/CaseDeletionLoggingService.java
src/main/java/uk/gov/hmcts/reform/ccd/util/SummaryStringLogBuilder.java
src/test/java/uk/gov/hmcts/reform/ccd/service/CaseDeletionLoggingServiceTest.java
src/test/java/uk/gov/hmcts/reform/ccd/util/SummaryStringLogBuilderTest.java

https://tools.hmcts.net/jira/browse/LAU-519
Fix case disposer log duplications
```
[ ] Yes
[x] No
```

LAU-519 Fix case disposer log duplications

---

src/functionalTest/java/uk/gov/hmcts/reform/ccd/CaseDeletionFunctionalTest.java
src/functionalTest/java/uk/gov/hmcts/reform/ccd/TestDataProvider.java
src/functionalTest/java/uk/gov/hmcts/reform/ccd/data/DeletionScenarios.java
src/functionalTest/java/uk/gov/hmcts/reform/ccd/utils/ElasticSearchTestUtils.java
src/functionalTest/java/uk/gov/hmcts/reform/ccd/utils/LauTestUtils.java
src/functionalTest/resources/application-functional.yaml

JIRA link (if applicable)
https://tools.hmcts.net/jira/browse/LAU-435
Change description
Enable ES for functional tests
```
[ ] Yes
[x] No
```

LAU-435 Enable ES for functional tests

---

src/functionalTest/java/uk/gov/hmcts/reform/ccd/TestDataProvider.java
src/functionalTest/java/uk/gov/hmcts/reform/ccd/helper/GlobalSearchIndexCreator.java

JIRA link (if applicable)
https://tools.hmcts.net/jira/browse/LAU-435
Change description
Enable ES for functional tests
```
[ ] Yes
[x] No
```

Remove global search API call for functional tests

---

charts/ccd-case-disposer/Chart.yaml

https://tools.hmcts.net/jira/browse/LAU-548
This change is upgrade 8.0.19
```
[ ] Yes
[x] No
```

LAU-548 update ccd to version 8

---

charts/ccd-case-disposer/Chart.yaml
config/owasp/suppressions.xml

https://tools.hmcts.net/jira/browse/LAU-548
This Change is to upgrade elastic search 7.8.3
```
[ ] Yes
[x] No
```

LAU-548 remove suppression related to snake

---

build.gradle
gradle/wrapper/gradle-wrapper.properties

https://tools.hmcts.net/jira/browse/LAU-548
This change is to upgrade gradle 6.9 to 7.4.2
```
[ ] Yes
[x] No
```

LAU-548 gradle upgrade 7.4.2

---

src/functionalTest/java/uk/gov/hmcts/reform/ccd/utils/DatabaseTestUtils.java

Add await in DatabaseTestUtils for functional tests
```
[ ] Yes
[x] No
```

Add await in DatabaseTestUtils

---

charts/ccd-case-disposer/Chart.yaml
src/integrationTest/java/uk/gov/hmcts/reform/ccd/ApplicationBootstrapIntegrationTest.java
src/integrationTest/java/uk/gov/hmcts/reform/ccd/CaseDeletionIntegrationTest.java
src/integrationTest/java/uk/gov/hmcts/reform/ccd/data/TestDataProvider.java
src/integrationTest/java/uk/gov/hmcts/reform/ccd/utils/DocumentRemoteDeletionVerifier.java
src/integrationTest/java/uk/gov/hmcts/reform/ccd/utils/LauRemoteDeletionVerifier.java
src/integrationTest/java/uk/gov/hmcts/reform/ccd/utils/RemoteDeletionVerifier.java
src/integrationTest/java/uk/gov/hmcts/reform/ccd/utils/RoleRemoteDeletionVerifier.java
src/main/java/uk/gov/hmcts/reform/ccd/data/model/CaseData.java
src/main/java/uk/gov/hmcts/reform/ccd/service/CaseDeletionService.java
src/main/java/uk/gov/hmcts/reform/ccd/service/remote/DisposeDocumentsRemoteOperation.java
src/main/java/uk/gov/hmcts/reform/ccd/service/remote/DisposeElasticsearchRemoteOperation.java
src/main/java/uk/gov/hmcts/reform/ccd/service/remote/DisposeRemoteOperation.java
src/main/java/uk/gov/hmcts/reform/ccd/service/remote/DisposeRoleAssignmentsRemoteOperation.java
src/main/java/uk/gov/hmcts/reform/ccd/service/remote/RemoteDisposeService.java
src/test/java/uk/gov/hmcts/reform/ccd/service/CaseDeletionServiceTest.java
src/test/java/uk/gov/hmcts/reform/ccd/service/remote/DisposeDocumentsRemoteOperationTest.java
src/test/java/uk/gov/hmcts/reform/ccd/service/remote/DisposeElasticsearchRemoteOperationTest.java
src/test/java/uk/gov/hmcts/reform/ccd/service/remote/DisposeRoleAssignmentsRemoteOperationTest.java
src/test/java/uk/gov/hmcts/reform/ccd/service/remote/RemoteDisposeServiceTest.java

https://tools.hmcts.net/jira/browse/LAU-558
Refactor case disposer remote operations
```
[ ] Yes
[x] No
```

LAU-558 Refactor case disposer remote operations

---

Jenkinsfile_CNP
Jenkinsfile_nightly

https://tools.hmcts.net/jira/browse/LAU-541
Update nightly build cron
```
[ ] Yes
[ ] No
```

LAU-541 update nightly build cron.

---

Jenkinsfile_nightly

https://tools.hmcts.net/jira/browse/LAU-541
Update schedule run time.
```
[ ] Yes
[x] No
```

LAU-541: Update nightly schedule.

---

build.gradle

https://tools.hmcts.net/jira/browse/LAU-569
Update postgresql lib.
```
[ ] Yes
[x] No
```

LAU-569: Update ppstgresql.

---

config/owasp/suppressions.xml

https://tools.hmcts.net/jira/browse/LAU-575
This change is to suppress CVE
```
[ ] Yes
[x] No
```

LAU-575 Suppressing CVE

---

.github/workflows/ci.yml

https://tools.hmcts.net/jira/browse/LAU-555
Update workflow action versions.
```
[ ] Yes
[x] No
```

LAU-555: Updated workflow actions.

---

config/owasp/suppressions.xml

https://tools.hmcts.net/jira/browse/LAU-584
This change is to suppress CVE
```
[ ] Yes
[x] No
```

LAU-584 suppressing CVE

---

build.gradle
config/owasp/suppressions.xml

https://tools.hmcts.net/jira/browse/LAU-586
This change is to suppress CVE
```
[ ] Yes
[x] No
```

LAU-586 suppressing CVE

---

charts/ccd-case-disposer/Chart.yaml
charts/ccd-case-disposer/values.preview.template.yaml

https://tools.hmcts.net/jira/browse/LAU-571
This change is to upgrade logstash
```
[ ] Yes
[x] No
```

LAU-571 logstash version upgrade

---

build.gradle

Update owasp version
Update owasp version
```
[ ] Yes
[x] No
```

Update onswap version

---

.dependabot/config.yml
.github/dependabot.yml

https://tools.hmcts.net/jira/browse/LAU-604
This change is to configure Dependabot with newer version
```
[ ] Yes
[x] No
```

LAU-604 configuring dependabot newer version

---

.github/workflows/ci.yml
Dockerfile
acb.tpl.yaml
build.gradle
config/owasp/suppressions.xml
src/integrationTest/java/uk/gov/hmcts/reform/ccd/config/es/ElasticSearchIndexCreator.java

https://tools.hmcts.net/jira/browse/LAU-605
Upgrade Java from 11 to 17 for ccd-case-disposer
```
[ ] Yes
[x] No
```

Upgrade java to v17

---

.github/dependabot.yml
Jenkinsfile_CNP
bin/load-preview-environment-variables.sh
build.gradle
charts/ccd-case-disposer/Chart.yaml
charts/ccd-case-disposer/values.preview.template.yaml

https://tools.hmcts.net/jira/browse/LAU-611
This change is to configure dependabot
```
[ ] Yes
[x] No
```

LAU-611 Dependabot configuration

---

Jenkinsfile_CNP
bin/load-preview-environment-variables.sh
charts/ccd-case-disposer/values.preview.template.yaml

https://tools.hmcts.net/jira/browse/LAU-603
This change is to change .internal
```
[ ] Yes
[x] No
```

LAU-603 changing .internal for elastic search

---

build.gradle

Remove unnecessary dependency

---

config/owasp/suppressions.xml

https://tools.hmcts.net/jira/browse/LAU-618
This change is to fix CVE-2022-1471
```
[ ] Yes
[x] No
```

LAU-618 suppress CVE-2022-1471

---

build.gradle
config/owasp/suppressions.xml

https://tools.hmcts.net/jira/browse/CCD-4454
update to snakeyaml
```
[ ] Yes
[X] No
```

CCD-4454 : Fix for CVE-2022-1471

---

build.gradle

CVE-2023-20861 fix
```
[ ] Yes
[x] No
```

CVE-2023-20861 springFramework fix

---

Jenkinsfile_CNP

https://tools.hmcts.net/jira/browse/LAU-615
This change is to change URL for elastic search
```
[ ] Yes
[x] No
```

LAU-615 changing elastic search url

---

build.gradle
config/owasp/suppressions.xml

https://tools.hmcts.net/jira/browse/LAU-681
Suppressing CVE that is disputed as not a CVE
```
[ ] Yes
[x] No
```

LAU-681 suppress CVE-2023-35116

---

lib/applicationinsights.json

Fix app insights connection string
Fix app insights connection string
```
[ ] Yes
[x] No
```

Fix app insights connection string

---

build.gradle

https://tools.hmcts.net/jira/browse/LAU-708
Bump up dependencies
```
[ ] Yes
[x] No
```

LAU-708 bump up dependencies

---

Jenkinsfile_CNP
build.gradle
src/contractTest/java/uk/gov/hmcts/reform/ccd/SpringBootContractBaseTest.java
src/contractTest/java/uk/gov/hmcts/reform/ccd/consumer/wa/TaskManagerDeleteTaskConsumerTest.java
src/contractTest/resources/application.properties

Pact testing

---

Jenkinsfile_CNP

Fixed the pipeline pact role issue

---

Jenkinsfile_CNP
Jenkinsfile_nightly
charts/ccd-case-disposer/Chart.yaml
charts/ccd-case-disposer/values.preview.template.yaml
charts/ccd-case-disposer/values.yaml
config/owasp/suppressions.xml
src/functionalTest/java/uk/gov/hmcts/reform/ccd/CaseDeletionFunctionalTest.java
src/functionalTest/java/uk/gov/hmcts/reform/ccd/TestDataProvider.java
src/functionalTest/java/uk/gov/hmcts/reform/ccd/data/DeletionScenarios.java
src/functionalTest/java/uk/gov/hmcts/reform/ccd/parameter/TestParameterResolver.java
src/functionalTest/java/uk/gov/hmcts/reform/ccd/utils/TaskDeleteTestUtils.java
src/functionalTest/resources/application-functional.yaml
src/integrationTest/java/uk/gov/hmcts/reform/ccd/config/TestParameterResolver.java
src/integrationTest/java/uk/gov/hmcts/reform/ccd/config/WireMockStubs.java
src/integrationTest/java/uk/gov/hmcts/reform/ccd/constants/TestConstants.java
src/integrationTest/java/uk/gov/hmcts/reform/ccd/utils/TasksRemoteDeletionVerifier.java
src/integrationTest/resources/application-test.yaml
src/main/java/uk/gov/hmcts/reform/ccd/data/tm/DeleteCaseTasksAction.java
src/main/java/uk/gov/hmcts/reform/ccd/data/tm/DeleteTasksRequest.java
src/main/java/uk/gov/hmcts/reform/ccd/parameter/DefaultParameterResolver.java
src/main/java/uk/gov/hmcts/reform/ccd/parameter/ParameterResolver.java
src/main/java/uk/gov/hmcts/reform/ccd/service/remote/DisposeTasksRemoteOperation.java
src/main/java/uk/gov/hmcts/reform/ccd/util/RestConstants.java
src/main/java/uk/gov/hmcts/reform/ccd/util/log/TasksDeletionRecordHolder.java
src/main/resources/application.yaml
src/test/java/uk/gov/hmcts/reform/ccd/parameter/DefaultParameterResolverTest.java
src/test/java/uk/gov/hmcts/reform/ccd/service/remote/DisposeTaskRemoteOperationTest.java
src/test/java/uk/gov/hmcts/reform/ccd/util/log/TaskDeleteRecordHolderTest.java

https://tools.hmcts.net/jira/browse/LAU-545
This change is for task deletion
```
[ ] Yes
[x] No
```

Lau task deletion

---

charts/ccd-case-disposer/Chart.yaml

https://tools.hmcts.net/jira/browse/LAU-799
Bump job chart version
```
[ ] Yes
[x] No
```

LAU-799 bump job chart version to the latest

---

charts/ccd-case-disposer/Chart.yaml

https://tools.hmcts.net/jira/browse/LAU-831
Upgrade charts-job to latest 2.1.1
```
[ ] Yes
[x] No
```

LAU-831 upgrade charts-job to latest

---

acb.tpl.yaml

https://tools.hmcts.net/jira/browse/LAU-834
Remove keep: true and add retries and retryDelay options

LAU-834 fix image pull failures on jenkins

---

acb.tpl.yaml

Added retries to missed blocks on initial PR

LAU-834 add retries to missed blocks

---

charts/ccd-case-disposer/values.aat.template.yaml

https://tools.hmcts.net/jira/secure/RapidBoard.jspa?rapidView=1382&projectKey=CCD&view=detail&selectedIssue=CCD-5162
Updating values.aat.template.yaml with V15 secrets for staging
```
[ ] Yes
[x] No
```

Updating staging with V15 secrets

---

build.gradle

Fix mutation test 
```
[ ] Yes
[ ] No
```

mutation-test-fix

---

charts/ccd-case-disposer/Chart.yaml
charts/ccd-case-disposer/values.yaml

Add missing bracket to fix master branch

---

src/main/java/uk/gov/hmcts/reform/ccd/ApplicationExecutor.java
src/test/java/uk/gov/hmcts/reform/ccd/ApplicationExecutorTest.java

https://tools.hmcts.net/jira/browse/LAU-979
The code had a bug where the request limit is not reached for single cases (with no case links)
```
[ ] Yes
[x] No
```

Fix request limit bug.

---

Jenkinsfile_nightly

Fix nightly build
Fix nightly build
```
[ ] Yes
[x] No
```

Fix nightly build

---

Dockerfile
README.md
build.gradle

Enable fortify scan
```
[ ] Yes
[x] No
```

Enable fortify

---

src/main/java/uk/gov/hmcts/reform/ccd/service/remote/DisposeElasticsearchRemoteOperation.java
src/test/java/uk/gov/hmcts/reform/ccd/service/remote/DisposeElasticsearchRemoteOperationTest.java

Es client exception handling is not covering all scenarios, this problem was highlighted  by perf test team.
```
[ ] Yes
[x] No
```

Make ES exception handling more generic.

---

src/functionalTest/java/uk/gov/hmcts/reform/ccd/parameter/TestParameterResolver.java
src/integrationTest/java/uk/gov/hmcts/reform/ccd/config/TestParameterResolver.java
src/main/java/uk/gov/hmcts/reform/ccd/ApplicationExecutor.java
src/main/java/uk/gov/hmcts/reform/ccd/parameter/DefaultParameterResolver.java
src/main/java/uk/gov/hmcts/reform/ccd/parameter/ParameterResolver.java
src/main/java/uk/gov/hmcts/reform/ccd/util/CcdDisposerClock.java
src/main/resources/application.yaml
src/test/java/uk/gov/hmcts/reform/ccd/ApplicationExecutorTest.java
src/test/java/uk/gov/hmcts/reform/ccd/parameter/DefaultParameterResolverTest.java

https://tools.hmcts.net/jira/browse/LAU-1089
Add a cut-off time, if disposer overruns.
```
[ ] Yes
[x] No
```

LAU-1089 ccd disposer cut off time

---

README.md

Dummy README update to test what happens with perftest environment
```
[ ] Yes
[x] No
```

whitespace change

---

Dockerfile

Bump appinsights agent version.

Bump appinsights agent versions

---

build.gradle
src/main/java/uk/gov/hmcts/reform/ccd/service/CaseDeletionLoggingService.java

https://tools.hmcts.net/jira/browse/LAU-1098
Display all simulated logs in batches
```
[ ] Yes
[x] No
```

LAU-1098 simulated logs in batch

---

charts/ccd-case-disposer/Chart.yaml

Upgrade job to oci version
```
[ ] Yes
[x] No
```

Upgrade chart job to oci version

---

src/main/java/uk/gov/hmcts/reform/ccd/service/CaseDeletionLoggingService.java
src/main/java/uk/gov/hmcts/reform/ccd/util/LogConstants.java
src/main/java/uk/gov/hmcts/reform/ccd/util/SummaryStringLogBuilder.java
src/test/java/uk/gov/hmcts/reform/ccd/service/CaseDeletionLoggingServiceTest.java
src/test/java/uk/gov/hmcts/reform/ccd/util/SummaryStringLogBuilderTest.java

https://tools.hmcts.net/jira/browse/LAU-1112
Adding deletion summary by caseType
```
[ ] Yes
[x] No
```

LAU-1112 adding casetype results in deletion summary

---

lib/applicationinsights.json

Do not send postgresql dependency messages to app insights
```
[ ] Yes
[x] No
```

Filter out dependency messages on app insights

---

src/integrationTest/java/uk/gov/hmcts/reform/ccd/config/WireMockStubs.java
src/integrationTest/java/uk/gov/hmcts/reform/ccd/constants/TestConstants.java
src/integrationTest/java/uk/gov/hmcts/reform/ccd/data/DeletionScenarios.java
src/integrationTest/resources/scenarios/S-035-deletable-failed-cases-due-to-log-and-audit-exception.sql
src/main/java/uk/gov/hmcts/reform/ccd/ApplicationExecutor.java
src/main/java/uk/gov/hmcts/reform/ccd/service/CaseDeletionService.java
src/test/java/uk/gov/hmcts/reform/ccd/ApplicationExecutorTest.java
src/test/java/uk/gov/hmcts/reform/ccd/service/CaseDeletionServiceTest.java

https://tools.hmcts.net/jira/browse/LAU-1092
Allow rollback to work on receiving an error from LAU
```
[ ] Yes
[x] No
```

LAU-1092 allow transaction to work on LAU error

---

src/main/java/uk/gov/hmcts/reform/ccd/util/LogConstants.java

https://tools.hmcts.net/jira/browse/LAU-1127
Remove leftovers from summary table removal

LAU-1127 remove leftover from summary table removal

---

.github/PULL_REQUEST_TEMPLATE.md
build.gradle

https://tools.hmcts.net/jira/browse/CME-527
Replace jitpack with azure artifactory
```
[ ] Yes
[x] No
```

CME-527 replace jitpack with azure artifactory

---

charts/ccd-case-disposer/Chart.yaml
charts/ccd-case-disposer/values.preview.template.yaml

https://tools.hmcts.net/jira/browse/LAU-746
See ticket comment for more info
```
[] Yes
[x] No
```

Update ccd charts
